### PR TITLE
Fixing #26 and a random grammar mistake

### PR DESCRIPTION
**Pull request by sk22**
You are welcome. :)

### CODE REVIEW

**Comment by leo** [comment]
This is a really shitty problem and I've worked on it several times personally. Sadly, your solution won't help us here... 😢 

The reason for that is that `100vh` on mobile Safari means the whole window, not the whole window without the top and bottom bar. In turn, the content with `100vh` will always be longer than the actual space in the browser (=> unnecessary scrollbar).

**Comment by sk22** [comment]
What I've just commented does not solve the problem you've mentioned above.

**Comment by sk22** [comment]
But you could actually see that side effect of 100vh as a feature (somewhat):
If you wanna get rid of the bars, you can scroll down and see the page in something like a full-screen mode.

**Comment by sk22** [comment]
At least that's what happens on Chrome... Probably Safari's bars persist, that'd be shitty indeed.

**Comment by leo** [comment]
That's correct, yes. But I don't want the front page and short posts to be scrollable when viewing them in Safari on mobile... 🤔

**Comment by sk22** [comment]
Yeah, I see... What could be done instead of my solution is to add an ID to the correct div, for that you'd have to overwrite the default document (which is like ejecting from a create-react-app: meh.)

**Comment by leo** [comment]
That sounds like a good idea!

**Comment by sk22** [comment]
Kinda—at least it should work.

**Comment by sk22** [comment]
Another thought I had was to query the react root like that:
`div[data-reactroot]` (not sure how the attribute is called exactly, since I'm on my phone right now)

**Comment by leo** [comment]
Closing! I don't think supporting that plugin is important. But thanks for the effort! 😊

**Pull request closed without merging**
